spring:
  cloud:
    gateway:
      routes:
        - id: analysis-route
          uri: lb://service-analysis
          predicates:
            - Path=/api/analysis/**

        - id: code-sandbox-route
          uri: lb://service-code-sandbox
          predicates:
            - Path=/api/codesandbox/**

        - id: teaching-route
          uri: lb://service-teaching
          predicates:
            - Path=/api/teaching/**

        - id: practice-route
          uri: lb://service-practice
          predicates:
            - Path=/api/practice/**

        - id: user-route
          uri: lb://service-user
          predicates:
            - Path=/user/**