server:
  port: 9050
spring:
  application:
    name: service-evaluation
  cloud:
    nacos:
      server-addr: 127.0.0.1:8848
      config:
        import-check:
          enabled: false
  #数据库配置
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/hbwl_evaluation
      username: root
      password: 123456
    type: com.alibaba.druid.pool.DruidDataSource

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  type-aliases-package: com.hbwl.pojo

#关闭日志打印
logging:
  level:
    com.alibaba.nacos: off
    com.alibaba.csp.sentinel: off