server:
  port: 9020
  #避免流式返回乱码
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true

spring:
  application:
    name: service-teaching
  config:
    import:
      - nacos:service-analysis.yaml #暂时使用analysis模块的llm配置
  cloud:
    nacos:
      server-addr: 127.0.0.1:8848
      config:
        import-check:
          enabled: false
  #数据库配置
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/hbwl_teaching
      password: 123456
      username: root
    type: com.alibaba.druid.pool.DruidDataSource
  servlet:
    multipart:
      max-file-size: 20MB
  #Redis配置
  data:
    redis:
      host: localhost
      port: 6379
      password:
      database: 0
      lettuce:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 0
          max-wait: -1ms
      timeout: 5000ms

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  type-aliases-package: com.hbwl.pojo

#文件传输
file:
  upload-dir: ./uploads/files/
  max-size: 20 * 1024 * 1024 #20MB

#Agent调用频率控制
agent:
  max-call-per-hour: 100

#关闭日志打印
logging:
  level:
    com.alibaba.nacos: off
    com.alibaba.csp.sentinel: off